eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 2000
spring:
  application:
    name: taxapy-taxista-server
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
          notification-in:
            destination: SaveNotification
            contentType: application/json
          notification-out:
            destination: SaveNotification
            contentType: application/json
          notificationD-in:
            destination: DeleteNotification
            contentType: application/json
          notificationD-out:
            destination: DeleteNotification
            contentType: application/json
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: integrador
    url: jdbc:mysql://taxappy-db.ccw8ocfn0bga.us-east-1.rds.amazonaws.com:3306/taxista?serverTimezone=UTC
    username: taxappy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
